/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lwc;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class hrc extends javax.swing.JFrame {

    /**
     * Creates new form hrc
     */
    public hrc() {
        initComponents();
        p.setBackground(Color.orange);
        setProfile();
        setPrescResp();
        
          presc.setEditable(false);
                tmed.setEditable(false);
                tmcentre.setEditable(false);
                tmcontact.setEditable(false);
                odate.setEditable(false);
         
         
         
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        p = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        vfname = new javax.swing.JTextField();
        vdob = new javax.swing.JTextField();
        vaddress = new javax.swing.JTextField();
        vcontact = new javax.swing.JTextField();
        vecontact = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        vid = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tcomp = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        resp = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();
        urgentcheckbox = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        presc = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        porder = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tmed = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tmcentre = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tmcontact = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        odate = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        vdid = new javax.swing.JTextField();
        vdoctor = new javax.swing.JTextField();
        vqual = new javax.swing.JTextField();
        vhosp = new javax.swing.JTextField();
        vdcontact = new javax.swing.JTextField();
        vdemail = new javax.swing.JTextField();
        vhid = new javax.swing.JTextField();
        vhw = new javax.swing.JTextField();
        vhaddress = new javax.swing.JTextField();
        vhcontact = new javax.swing.JTextField();
        vhemail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        oldpass = new javax.swing.JPasswordField();
        newpass = new javax.swing.JPasswordField();
        confpass = new javax.swing.JPasswordField();
        savepass = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("LIVE WITH COVID");

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pLayout = new javax.swing.GroupLayout(p);
        p.setLayout(pLayout);
        pLayout.setHorizontalGroup(
            pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout)
                .addContainerGap())
        );
        pLayout.setVerticalGroup(
            pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(logout))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel5.setText("Name");

        jLabel6.setText("DOB");

        jLabel8.setText("Contact");

        jLabel12.setText("Emergency Contact");

        vdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vdobActionPerformed(evt);
            }
        });

        vcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vcontactActionPerformed(evt);
            }
        });

        jLabel15.setText("Address");

        jLabel22.setText("ID");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("MY PROFILE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(vaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(vcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(jLabel5)
                            .addComponent(jLabel22)
                            .addComponent(jLabel33))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vecontact, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vdob, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vfname, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vid, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(555, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(vid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(vdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(vaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(vcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(vecontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Profile", jPanel1);

        jLabel2.setText("Complications");

        jLabel3.setText("Response");

        tcomp.setColumns(20);
        tcomp.setRows(5);
        jScrollPane1.setViewportView(tcomp);

        resp.setColumns(20);
        resp.setRows(5);
        jScrollPane2.setViewportView(resp);

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        urgentcheckbox.setText("Need Urgent Attention");
        urgentcheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urgentcheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(urgentcheckbox)
                    .addComponent(submit))
                .addGap(0, 325, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(urgentcheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submit))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Talk with Doctor", jPanel2);

        presc.setColumns(20);
        presc.setRows(5);
        jScrollPane3.setViewportView(presc);

        jLabel4.setText("Prescription");

        porder.setText("Order Prescription");
        porder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porderActionPerformed(evt);
            }
        });

        jLabel7.setText("Telemedicine Centre ID");

        tmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmedActionPerformed(evt);
            }
        });

        jLabel16.setText("Telemedicine Centre Name");

        jLabel17.setText("Contact No");

        jLabel18.setText("Order Date");

        odate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(porder)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(34, 34, 34)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(odate, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(tmcontact, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(tmcentre, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(tmed))
                                .addGap(114, 114, 114))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18))
                        .addGap(267, 267, 267))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(porder)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tmed, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tmcentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(tmcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(odate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Prescription", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setText("Doctor ID");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 61, -1, -1));

        jLabel23.setText("Name");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 99, -1, -1));

        jLabel24.setText("Hospital");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 138, -1, -1));

        jLabel25.setText("Qualification");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 179, -1, -1));

        jLabel26.setText("Contact");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 217, -1, -1));

        jLabel27.setText("email");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 255, -1, -1));

        vdid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vdidActionPerformed(evt);
            }
        });
        jPanel5.add(vdid, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 58, 113, -1));
        jPanel5.add(vdoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 96, 113, -1));
        jPanel5.add(vqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 176, 113, -1));
        jPanel5.add(vhosp, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 135, 113, -1));

        vdcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vdcontactActionPerformed(evt);
            }
        });
        jPanel5.add(vdcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 214, 113, -1));
        jPanel5.add(vdemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 252, 113, -1));

        vhid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vhidActionPerformed(evt);
            }
        });
        jPanel5.add(vhid, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 58, 119, -1));

        vhw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vhwActionPerformed(evt);
            }
        });
        jPanel5.add(vhw, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 96, 119, -1));
        jPanel5.add(vhaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 135, 119, -1));
        jPanel5.add(vhcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 176, 119, -1));
        jPanel5.add(vhemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 214, 119, -1));

        jLabel11.setText("Healthworker ID");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 61, -1, -1));

        jLabel19.setText("Name");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 99, -1, -1));

        jLabel28.setText("Address");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 138, -1, -1));

        jLabel29.setText("Contact");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 179, -1, -1));

        jLabel30.setText("email");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 217, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("DOCTOR DETAILS");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 11, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("HEALTHWORKER DETAILS");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 11, -1, -1));

        jTabbedPane1.addTab("Doctor & Healthworker Details", jPanel5);

        jLabel10.setText("Enter Old Password");

        jLabel13.setText("Enter New Password");

        jLabel14.setText("Confirm New Password");

        savepass.setText("Save");
        savepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savepassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(savepass)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(confpass, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(newpass)
                            .addComponent(oldpass))))
                .addContainerGap(413, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(oldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(newpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(confpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(savepass)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 822, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Change Password", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setProfile(){
        try{
            String name=hrclogin.tuser.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","742000");
            String sql="select id,fname,lname,dob,address,location,contact,econtact,did,dfname,dlname,dcontact,demail,hospital,dlocation,qualification,"
                    + "hwid,hwfname,hwlname,hwcontact,hwemail,hwaddress,hwlocation,urgency from hrc,doctor,healthworker "
                    + "where hrc.doctorid=doctor.did and hrc.healthworkerid=healthworker.hwid and hrc.fname='"+name+"'";
            PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery(sql);
              if(rs.next()){
                String id=rs.getString("id");
                String fname=rs.getString("fname");
                String lname=rs.getString("lname");
                String dob=rs.getString("dob");
                String address=rs.getString("address");
                String location=rs.getString("location");
                String contact=rs.getString("contact");
                String econtact=rs.getString("econtact");
                String dfname=rs.getString("dfname");
                String hfname=rs.getString("hwfname");
                String did=rs.getString("did");
                String hid=rs.getString("hwid");
                String hosp=rs.getString("hospital");
                String qual=rs.getString("qualification");
                String dlname=rs.getString("dlname");
                String dcont=rs.getString("dcontact");
                String demail=rs.getString("demail");
                String dloc=rs.getString("dlocation");
                String hlname=rs.getString("hwlname");
                String haddress=rs.getString("hwaddress");
                String hloc=rs.getString("hwlocation");
                String hcont=rs.getString("hwcontact");
                String hemail=rs.getString("hwemail");
                vid.setText(id);
                vdid.setText(did);
                vhid.setText(hid);
                vfname.setText(fname+" "+lname);
                vdob.setText(dob);
                vaddress.setText(address+","+location);
                vcontact.setText(contact);
                vecontact.setText(econtact);
                vdoctor.setText(dfname+" "+dlname);
                vhosp.setText(hosp+","+dloc);
                vdcontact.setText(dcont);
                vdemail.setText(demail);
                vqual.setText(qual);
                vhw.setText(hfname+" "+hlname);
                vhaddress.setText(haddress+","+hloc);
                vhcontact.setText(hcont);
                vhemail.setText(hemail);
                 if(rs.getString("urgency").equals("Urgent"))
                    urgentcheckbox.setSelected(true);
                else{
                    urgentcheckbox.setSelected(false);}
              }
        }
        catch(Exception e){
          
        }
    }
    private void setPrescResp(){
        try{
            String id=vid.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","742000");
           String sql="select exists (select cid from report where report.rid='"+id+"')";           
            PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery(sql);
            if(rs.next()){
               int check=rs.getInt("exists (select cid from report where report.rid='"+id+"')");
               if(check==0){
               resp.setText("");
               presc.setText("");
               }
               else{
                   String sql1="select prscription,response from report,hrc where hrc.id=report.rid and hrc.id='"+id+"'ORDER BY cid DESC limit 1";
                    PreparedStatement pst1=conn.prepareStatement(sql1);
                    ResultSet rs1=pst1.executeQuery(sql1);
                    if(rs1.next()){
                        String response=rs1.getString("response");
                        String prescrip=rs1.getString("prscription"); 
                         if(response!=null){
                         resp.setText(response);}
                         if(prescrip != null){
                         presc.setText(prescrip);}
                    }
               }
              /*  String response=rs.getString("response");
                String prescrip=rs.getString("prscription");
             
                if(response!=null){
                resp.setText(response);}
                if(prescrip != null){
                presc.setText(prescrip);}
               
                presc.setEditable(false);
                tmed.setEditable(false);
                tmcentre.setEditable(false);
                tmcontact.setEditable(false);
                odate.setEditable(false);
                
            }*/
            }  
        }
        catch(Exception e){
              JOptionPane.showMessageDialog(null,e);
        }
    }
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
    
        try{
            SimpleDateFormat formatter=new SimpleDateFormat("dd/MM/yyyy");
            Date date=new Date();
            String id=vid.getText(); 
            String did=vdid.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","742000");
            String sql=" insert into report(rid,drid,cdate,complaints) values (?,?,?,? )";
            PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1, id);
            pst.setString(2, did);
            pst.setString(3, formatter.format(date));
            pst.setString(4, tcomp.getText());            
            pst.execute();
            JOptionPane.showMessageDialog(null,"Saved");
           
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void vdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vdobActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        new logas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void urgentcheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urgentcheckboxActionPerformed
          try{   
            if(urgentcheckbox.isSelected()){
            String id=vid.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","742000");
            String sql="update hrc set urgency='Urgent' where id='"+id+"'";
            PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();}
            else{
            String id=vid.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","742000");
            String sql="update hrc set urgency='Not Urgent' where id='"+id+"'";
            PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            }
           
        }   
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_urgentcheckboxActionPerformed

    private void porderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porderActionPerformed
      
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","742000");
            String sql="select tid from (select n.tid,COALESCE(t.ordercount,0)as ordercount from telemedicine n left join (select tmoid,count(*) as ordercount from tmedorder group by tmoid)t on n.tid=t.tmoid) as c where ordercount = (select min(ordercount) from (select n.tid,COALESCE(t.ordercount,0)as ordercount from telemedicine n left join (select tmoid,count(*) as ordercount from tmedorder group by tmoid)t on n.tid=t.tmoid) as c)";
            PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery(sql);
            if(rs.next()){
                String id=rs.getString("tid");
                tmed.setText(id);
            }
        }
           catch(Exception e){
           JOptionPane.showMessageDialog(null,e); 
        }
        try{
            SimpleDateFormat formatter=new SimpleDateFormat("dd/MM/yyyy");
            Date date=new Date();
            String id=tmed.getText(); 
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","742000");
            String sql=" select org_name,cnt_no from telemedicine where tid='"+id+"'";
            PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery(sql);
            if(rs.next()){
                
                tmcentre.setText(rs.getString("org_name"));
                tmcontact.setText(rs.getString("cnt_no"));
                odate.setText(formatter.format(date));         
            }
           
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
         
        try{   
            String id=vid.getText();
            String pres=presc.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","742000");
            String sql2="select cid from report where rid='"+id+"' and prscription='"+pres+"'";
            PreparedStatement pst1=conn.prepareStatement(sql2);
            ResultSet rs=pst1.executeQuery(sql2);
            if(rs.next()){
                
            String sql="insert into tmedorder (hrcid,drid,tmoid,orderdate,cid) values (?,?,?,?,?)";
            PreparedStatement pst=conn.prepareStatement(sql);
             pst.setString(1,id);
             pst.setString(2,vdid.getText());
             pst.setString(3,tmed.getText());
             pst.setString(4,odate.getText());
             pst.setString(5,rs.getString("cid"));
             
             pst.execute();
            JOptionPane.showMessageDialog(null,"saved");
        }   }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_porderActionPerformed

    private void odateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_odateActionPerformed

    private void tmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmedActionPerformed

    private void vhidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vhidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vhidActionPerformed

    private void vdidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vdidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vdidActionPerformed

    private void vdcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vdcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vdcontactActionPerformed

    private void vhwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vhwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vhwActionPerformed

    private void vcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vcontactActionPerformed

    private void savepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savepassActionPerformed
        try{

            String id=vid.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","742000");
            String sql="select password from hrc where id='"+id+"'";
            PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs=pst.executeQuery(sql);
            if(rs.next()){
                String pass=newpass.getText();
                if((rs.getString("password").equals(oldpass.getText())&&(newpass.getText().equals(confpass.getText())))){
                    String sql1="update hrc set password='"+pass+"' where id='"+id+"'";
                    PreparedStatement pst1=conn.prepareStatement(sql1);
                    pst1.execute();
                    JOptionPane.showMessageDialog(null,"Password changed");
                }
                else{
                    JOptionPane.showMessageDialog(null,"Password do not match");
                }
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_savepassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hrc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hrc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hrc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hrc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hrc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confpass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logout;
    private javax.swing.JPasswordField newpass;
    private javax.swing.JTextField odate;
    private javax.swing.JPasswordField oldpass;
    private javax.swing.JPanel p;
    private javax.swing.JButton porder;
    private javax.swing.JTextArea presc;
    private javax.swing.JTextArea resp;
    private javax.swing.JButton savepass;
    private javax.swing.JButton submit;
    private javax.swing.JTextArea tcomp;
    private javax.swing.JTextField tmcentre;
    private javax.swing.JTextField tmcontact;
    private javax.swing.JTextField tmed;
    private javax.swing.JCheckBox urgentcheckbox;
    private javax.swing.JTextField vaddress;
    private javax.swing.JTextField vcontact;
    private javax.swing.JTextField vdcontact;
    private javax.swing.JTextField vdemail;
    private javax.swing.JTextField vdid;
    private javax.swing.JTextField vdob;
    private javax.swing.JTextField vdoctor;
    private javax.swing.JTextField vecontact;
    private javax.swing.JTextField vfname;
    private javax.swing.JTextField vhaddress;
    private javax.swing.JTextField vhcontact;
    private javax.swing.JTextField vhemail;
    private javax.swing.JTextField vhid;
    private javax.swing.JTextField vhosp;
    private javax.swing.JTextField vhw;
    private javax.swing.JTextField vid;
    private javax.swing.JTextField vqual;
    // End of variables declaration//GEN-END:variables
}
